// <auto-generated />
using System;
using KB.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KB.Core.Migrations
{
    [DbContext(typeof(KbDbContext))]
    [Migration("20260316035803_InitialDatabase")]
    partial class InitialDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KB.Core.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Established")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ItemTypeId");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("KB.Core.Entities.ItemRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Established")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("RelatedItemId")
                        .HasColumnType("int");

                    b.Property<int>("RelationTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RelatedItemId");

                    b.HasIndex("RelationTypeId");

                    b.HasIndex("ItemId", "RelationTypeId", "RelatedItemId")
                        .IsUnique();

                    b.ToTable("ItemRelations", (string)null);
                });

            modelBuilder.Entity("KB.Core.Entities.ItemRelationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Relation")
                        .IsUnique();

                    b.ToTable("ItemRelationTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Project → Feature, Project → Sub-Project, Domain → Concept",
                            Relation = "Contains"
                        },
                        new
                        {
                            Id = 2,
                            Description = "inverse of Contains (optional if you traverse IncomingRelations)",
                            Relation = "BelongsTo"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Feature → Feature, Component → Component, Skill → Skill",
                            Relation = "DependsOn"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Feature → Requirement, Component → Feature",
                            Relation = "Implements"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Rule → Scope, Rule → Feature, Standard → Component",
                            Relation = "Governs"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Rule → Domain, Constraint → Project",
                            Relation = "AppliesTo"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Feature → Skill, Role → Skill",
                            Relation = "Requires"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Feature → Feature, Project → Project (inheritance/variation)",
                            Relation = "Extends"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Rule → Rule (precedence)",
                            Relation = "Overrides"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Constraint → Requirement, Rule → Rule",
                            Relation = "ConflictsWith"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Decision → Decision (evolution over time)",
                            Relation = "SupersededBy"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Concept → Concept, Technology → Skill (concrete instance of)",
                            Relation = "Exemplifies"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Generic catch-all for weak associations",
                            Relation = "RelatedTo"
                        });
                });

            modelBuilder.Entity("KB.Core.Entities.ItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ItemTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Recursive, can contain sub-projects",
                            Name = "Project"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bounded context / problem area (DDD influence)",
                            Name = "Domain"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Deliverable capability",
                            Name = "Feature"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Technical building block (service, lib, module)",
                            Name = "Component"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Functional or non-functional",
                            Name = "Requirement"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Things that limit decisions (time, budget, tech)",
                            Name = "Constraint"
                        },
                        new
                        {
                            Id = 7,
                            Description = "A governing directive",
                            Name = "Rule"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Boundary of applicability for rules",
                            Name = "Scope"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Capability, knowledge area, or technology",
                            Name = "Skill"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Persona or team function (Dev, Architect, QA...)",
                            Name = "Role"
                        },
                        new
                        {
                            Id = 11,
                            Description = "An ADR, a resolved choice with rationale",
                            Name = "Decision"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Abstract idea or domain term (ubiquitous language)",
                            Name = "Concept"
                        },
                        new
                        {
                            Id = 13,
                            Description = "A convention or coding standard",
                            Name = "Standard"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Language, framework, tool, platform",
                            Name = "Technology"
                        });
                });

            modelBuilder.Entity("KB.Core.Entities.Item", b =>
                {
                    b.HasOne("KB.Core.Entities.ItemType", "ItemType")
                        .WithMany("Items")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemType");
                });

            modelBuilder.Entity("KB.Core.Entities.ItemRelation", b =>
                {
                    b.HasOne("KB.Core.Entities.Item", "Item")
                        .WithMany("Relations")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KB.Core.Entities.Item", "RelatedItem")
                        .WithMany("IncomingRelations")
                        .HasForeignKey("RelatedItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KB.Core.Entities.ItemRelationType", "RelationType")
                        .WithMany("ItemRelations")
                        .HasForeignKey("RelationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("RelatedItem");

                    b.Navigation("RelationType");
                });

            modelBuilder.Entity("KB.Core.Entities.Item", b =>
                {
                    b.Navigation("IncomingRelations");

                    b.Navigation("Relations");
                });

            modelBuilder.Entity("KB.Core.Entities.ItemRelationType", b =>
                {
                    b.Navigation("ItemRelations");
                });

            modelBuilder.Entity("KB.Core.Entities.ItemType", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
